language: java
jdk:
    - oraclejdk8
    - oraclejdk7

install: /bin/true # this keeps 'gradle assemble' from being called which tries to sign the jars.
script: "gradle test"
    
notifications:
    email:
        - taxii-commits-list@lists.mitre.org
